local_repository() does not work with yarn_install()
Switch from `npm_install()` to `yarn_install()` in root
`WORKSPACE.bazel`, and:

```
DEBUG: /path/to/.cache/bazel/_bazel_to/3e5deae581a12e699fbb51399b46e727/external/build_bazel_rules_nodejs/index.bzl:65:14: node_repository attribute not set and no repository named 'nodejs_toolchains' exists; installing default node
DEBUG: /path/to/.cache/bazel/_bazel_to/3e5deae581a12e699fbb51399b46e727/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
INFO: Repository npm_alpha instantiated at:
  /path/to/src/bazel-nodejs-rollup-multi-package/WORKSPACE.bazel:17:13: in <toplevel>
  /path/to/.cache/bazel/_bazel_to/3e5deae581a12e699fbb51399b46e727/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  /path/to/.cache/bazel/_bazel_to/3e5deae581a12e699fbb51399b46e727/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:975:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm_alpha':
   Traceback (most recent call last):
        File "/path/to/.cache/bazel/_bazel_to/3e5deae581a12e699fbb51399b46e727/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 935, column 18, in _yarn_install_impl
                _symlink_file(repository_ctx, repository_ctx.attr.yarn_lock)
        File "/path/to/.cache/bazel/_bazel_to/3e5deae581a12e699fbb51399b46e727/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 605, column 27, in _symlink_file
                repository_ctx.symlink(f, _rerooted_workspace_path(repository_ctx, f))
Error in symlink: Unable to load package for //js/alpha:yarn.lock: Invalid package reference js/alpha crosses into repository @alpha: did you mean to use @alpha// instead?
ERROR: /path/to/src/bazel-nodejs-rollup-multi-package/WORKSPACE.bazel:17:13: fetching yarn_install rule //external:npm_alpha: Traceback (most recent call last):
        File "/path/to/.cache/bazel/_bazel_to/3e5deae581a12e699fbb51399b46e727/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 935, column 18, in _yarn_install_impl
                _symlink_file(repository_ctx, repository_ctx.attr.yarn_lock)
        File "/path/to/.cache/bazel/_bazel_to/3e5deae581a12e699fbb51399b46e727/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 605, column 27, in _symlink_file
                repository_ctx.symlink(f, _rerooted_workspace_path(repository_ctx, f))
Error in symlink: Unable to load package for //js/alpha:yarn.lock: Invalid package reference js/alpha crosses into repository @alpha: did you mean to use @alpha// instead?
ERROR: Skipping '@alpha//:bundle.bin': no such package '@npm_alpha//@bazel/rollup': Unable to load package for //js/alpha:yarn.lock: Invalid package reference js/alpha crosses into repository @alpha: did you mean to use @alpha// instead?
WARNING: Target pattern parsing failed.
ERROR: no such package '@npm_alpha//@bazel/rollup': Unable to load package for //js/alpha:yarn.lock: Invalid package reference js/alpha crosses into repository @alpha: did you mean to use @alpha// instead?
INFO: Elapsed time: 3.588s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: @alpha//
```